-- ============================================================================
-- EL_SAHA (الصحة) - Script de creation du schema relationnel
-- Oracle Database 10g Release 2
-- A executer avec le compte ELSAHA_ADMIN connecte a la base EL_SAHA
-- ============================================================================

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT ============================================================
PROMPT  NETTOYAGE DES ANCIENS OBJETS EL_SAHA
PROMPT ============================================================

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'PAIEMENT','FACTURE','DEMANDE_ANALYSE','ANALYSE','HOSPITALISATION',
      'ACTE_CONSULTATION','ACTE','PRESCRIPTION','MEDICAMENT','ORDONNANCE',
      'CONSULTATION','RENDEZ_VOUS','CHAMBRE','SERVICE','MEDECIN','PATIENT',
      'PERSONNE','CLINIQUE','JOURNAL_OPERATION'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;

  FOR s IN (
    SELECT sequence_name FROM user_sequences
    WHERE sequence_name IN (
      'SEQ_CLINIQUE','SEQ_PERSONNE','SEQ_PATIENT','SEQ_MEDECIN','SEQ_SERVICE',
      'SEQ_CHAMBRE','SEQ_RDV','SEQ_CONSULTATION','SEQ_ORDONNANCE',
      'SEQ_MEDICAMENT','SEQ_ACTE','SEQ_HOSPITALISATION','SEQ_ANALYSE',
      'SEQ_DEMANDE_ANALYSE','SEQ_FACTURE','SEQ_PAIEMENT','SEQ_JOURNAL'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

PROMPT ============================================================
PROMPT  CREATION DES TABLES DE REFERENCE
PROMPT ============================================================

CREATE TABLE CLINIQUE (
  ID_CLINIQUE       NUMBER(4)      CONSTRAINT PK_CLINIQUE PRIMARY KEY,
  NOM_CLINIQUE      VARCHAR2(80)   CONSTRAINT NN_CLINIQUE_NOM NOT NULL,
  VILLE             VARCHAR2(40)   CONSTRAINT NN_CLINIQUE_VILLE NOT NULL,
  ADRESSE           VARCHAR2(150)  CONSTRAINT NN_CLINIQUE_ADR NOT NULL,
  TELEPHONE         VARCHAR2(20),
  TYPE_CLINIQUE     VARCHAR2(20)   DEFAULT 'PRIVEE' NOT NULL,
  DATE_OUVERTURE    DATE,
  CONSTRAINT UQ_CLINIQUE_NOM_VILLE UNIQUE (NOM_CLINIQUE, VILLE),
  CONSTRAINT CK_CLINIQUE_TYPE CHECK (TYPE_CLINIQUE IN ('PUBLIQUE','PRIVEE','MIXTE'))
);

COMMENT ON TABLE CLINIQUE IS 'Etablissements de sante du reseau EL_SAHA';
COMMENT ON COLUMN CLINIQUE.TYPE_CLINIQUE IS 'PUBLIQUE, PRIVEE ou MIXTE';

CREATE TABLE PERSONNE (
  ID_PERSONNE       NUMBER(6)      CONSTRAINT PK_PERSONNE PRIMARY KEY,
  NOM               VARCHAR2(50)   CONSTRAINT NN_PERSONNE_NOM NOT NULL,
  PRENOM            VARCHAR2(50)   CONSTRAINT NN_PERSONNE_PRENOM NOT NULL,
  DATE_NAISSANCE    DATE           CONSTRAINT NN_PERSONNE_DN NOT NULL,
  SEXE              CHAR(1)        CONSTRAINT NN_PERSONNE_SEXE NOT NULL,
  ADRESSE           VARCHAR2(180),
  VILLE             VARCHAR2(40),
  TELEPHONE         VARCHAR2(20),
  EMAIL             VARCHAR2(100),
  DATE_CREATION     DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT CK_PERSONNE_SEXE CHECK (SEXE IN ('F','M')),
  CONSTRAINT CK_PERSONNE_DATE CHECK (DATE_NAISSANCE < DATE_CREATION),
  CONSTRAINT UQ_PERSONNE_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE PERSONNE IS 'Super-type relationnel commun aux patients et medecins';

CREATE TABLE PATIENT (
  ID_PATIENT        NUMBER(6)      CONSTRAINT PK_PATIENT PRIMARY KEY,
  ID_PERSONNE       NUMBER(6)      CONSTRAINT NN_PATIENT_PERSONNE NOT NULL,
  NUM_SECURITE_SOC  VARCHAR2(30),
  GROUPE_SANGUIN    VARCHAR2(3),
  ANTECEDENTS       VARCHAR2(500),
  ALLERGIES         VARCHAR2(500),
  PERSONNE_CONTACT  VARCHAR2(100),
  TEL_CONTACT       VARCHAR2(20),
  CONSTRAINT UQ_PATIENT_PERSONNE UNIQUE (ID_PERSONNE),
  CONSTRAINT UQ_PATIENT_NUMSS UNIQUE (NUM_SECURITE_SOC),
  CONSTRAINT FK_PATIENT_PERSONNE FOREIGN KEY (ID_PERSONNE)
    REFERENCES PERSONNE(ID_PERSONNE),
  CONSTRAINT CK_PATIENT_GROUPE CHECK
    (GROUPE_SANGUIN IN ('A+','A-','B+','B-','AB+','AB-','O+','O-'))
);

COMMENT ON TABLE PATIENT IS 'Sous-type relationnel de PERSONNE pour les patients';

CREATE TABLE SERVICE (
  ID_SERVICE        NUMBER(4)      CONSTRAINT PK_SERVICE PRIMARY KEY,
  NOM_SERVICE       VARCHAR2(60)   CONSTRAINT NN_SERVICE_NOM NOT NULL,
  ID_CLINIQUE       NUMBER(4)      CONSTRAINT NN_SERVICE_CLINIQUE NOT NULL,
  ID_MEDECIN_CHEF   NUMBER(6),
  ETAGE             NUMBER(2),
  TELEPHONE_INTERNE VARCHAR2(10),
  CAPACITE_LITS     NUMBER(4) DEFAULT 0 NOT NULL,
  CONSTRAINT UQ_SERVICE UNIQUE (ID_CLINIQUE, NOM_SERVICE),
  CONSTRAINT FK_SERVICE_CLINIQUE FOREIGN KEY (ID_CLINIQUE)
    REFERENCES CLINIQUE(ID_CLINIQUE),
  CONSTRAINT CK_SERVICE_CAPACITE CHECK (CAPACITE_LITS >= 0)
);

CREATE TABLE MEDECIN (
  ID_MEDECIN        NUMBER(6)      CONSTRAINT PK_MEDECIN PRIMARY KEY,
  ID_PERSONNE       NUMBER(6)      CONSTRAINT NN_MEDECIN_PERSONNE NOT NULL,
  NUM_ORDRE         VARCHAR2(30)   CONSTRAINT NN_MEDECIN_ORDRE NOT NULL,
  SPECIALITE        VARCHAR2(60)   CONSTRAINT NN_MEDECIN_SPEC NOT NULL,
  GRADE             VARCHAR2(25)   DEFAULT 'GENERALISTE' NOT NULL,
  DATE_RECRUTEMENT  DATE           CONSTRAINT NN_MEDECIN_RECRUT NOT NULL,
  SALAIRE           NUMBER(10,2),
  ID_CLINIQUE       NUMBER(4)      CONSTRAINT NN_MEDECIN_CLINIQUE NOT NULL,
  ACTIF             CHAR(1) DEFAULT 'O' NOT NULL,
  CONSTRAINT UQ_MEDECIN_PERSONNE UNIQUE (ID_PERSONNE),
  CONSTRAINT UQ_MEDECIN_ORDRE UNIQUE (NUM_ORDRE),
  CONSTRAINT FK_MEDECIN_PERSONNE FOREIGN KEY (ID_PERSONNE)
    REFERENCES PERSONNE(ID_PERSONNE),
  CONSTRAINT FK_MEDECIN_CLINIQUE FOREIGN KEY (ID_CLINIQUE)
    REFERENCES CLINIQUE(ID_CLINIQUE),
  CONSTRAINT CK_MEDECIN_GRADE CHECK
    (GRADE IN ('GENERALISTE','SPECIALISTE','MAITRE_ASSISTANT','PROFESSEUR')),
  CONSTRAINT CK_MEDECIN_SALAIRE CHECK (SALAIRE IS NULL OR SALAIRE > 0),
  CONSTRAINT CK_MEDECIN_ACTIF CHECK (ACTIF IN ('O','N'))
);

ALTER TABLE SERVICE ADD CONSTRAINT FK_SERVICE_CHEF
  FOREIGN KEY (ID_MEDECIN_CHEF) REFERENCES MEDECIN(ID_MEDECIN);

CREATE TABLE CHAMBRE (
  ID_CHAMBRE        NUMBER(5)      CONSTRAINT PK_CHAMBRE PRIMARY KEY,
  ID_SERVICE        NUMBER(4)      CONSTRAINT NN_CHAMBRE_SERVICE NOT NULL,
  NUMERO_CHAMBRE    VARCHAR2(10)   CONSTRAINT NN_CHAMBRE_NUM NOT NULL,
  TYPE_CHAMBRE      VARCHAR2(20)   DEFAULT 'DOUBLE' NOT NULL,
  NOMBRE_LITS       NUMBER(2)      DEFAULT 2 NOT NULL,
  TARIF_JOURNALIER  NUMBER(10,2)   CONSTRAINT NN_CHAMBRE_TARIF NOT NULL,
  DISPONIBLE        CHAR(1) DEFAULT 'O' NOT NULL,
  CONSTRAINT UQ_CHAMBRE_SERVICE_NUM UNIQUE (ID_SERVICE, NUMERO_CHAMBRE),
  CONSTRAINT UQ_CHAMBRE_SERVICE_ID UNIQUE (ID_CHAMBRE, ID_SERVICE),
  CONSTRAINT FK_CHAMBRE_SERVICE FOREIGN KEY (ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE),
  CONSTRAINT CK_CHAMBRE_TYPE CHECK (TYPE_CHAMBRE IN ('INDIVIDUELLE','DOUBLE','COLLECTIVE','SOINS_INTENSIFS')),
  CONSTRAINT CK_CHAMBRE_LITS CHECK (NOMBRE_LITS > 0),
  CONSTRAINT CK_CHAMBRE_TARIF CHECK (TARIF_JOURNALIER > 0),
  CONSTRAINT CK_CHAMBRE_DISPO CHECK (DISPONIBLE IN ('O','N'))
);

PROMPT ============================================================
PROMPT  CREATION DES TABLES TRANSACTIONNELLES
PROMPT ============================================================

CREATE TABLE RENDEZ_VOUS (
  ID_RDV             NUMBER(8)     CONSTRAINT PK_RENDEZ_VOUS PRIMARY KEY,
  ID_PATIENT         NUMBER(6)     CONSTRAINT NN_RDV_PATIENT NOT NULL,
  ID_MEDECIN         NUMBER(6)     CONSTRAINT NN_RDV_MEDECIN NOT NULL,
  ID_SERVICE         NUMBER(4)     CONSTRAINT NN_RDV_SERVICE NOT NULL,
  DATE_RDV           DATE          CONSTRAINT NN_RDV_DATE NOT NULL,
  HEURE_RDV          VARCHAR2(5)   CONSTRAINT NN_RDV_HEURE NOT NULL,
  MOTIF              VARCHAR2(250),
  STATUT             VARCHAR2(20) DEFAULT 'PLANIFIE' NOT NULL,
  DATE_CREATION      DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_RDV_PATIENT FOREIGN KEY (ID_PATIENT)
    REFERENCES PATIENT(ID_PATIENT),
  CONSTRAINT FK_RDV_MEDECIN FOREIGN KEY (ID_MEDECIN)
    REFERENCES MEDECIN(ID_MEDECIN),
  CONSTRAINT FK_RDV_SERVICE FOREIGN KEY (ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE),
  CONSTRAINT UQ_RDV_MEDECIN_CRENEAU UNIQUE (ID_MEDECIN, DATE_RDV, HEURE_RDV),
  CONSTRAINT CK_RDV_HEURE CHECK (REGEXP_LIKE(HEURE_RDV, '^[0-2][0-9]:[0-5][0-9]$')),
  CONSTRAINT CK_RDV_STATUT CHECK
    (STATUT IN ('PLANIFIE','CONFIRME','ANNULE','REALISE','ABSENT'))
);

CREATE TABLE CONSULTATION (
  ID_CONSULTATION    NUMBER(8)     CONSTRAINT PK_CONSULTATION PRIMARY KEY,
  ID_RDV             NUMBER(8),
  ID_PATIENT         NUMBER(6)     CONSTRAINT NN_CONSULT_PATIENT NOT NULL,
  ID_MEDECIN         NUMBER(6)     CONSTRAINT NN_CONSULT_MEDECIN NOT NULL,
  ID_SERVICE         NUMBER(4)     CONSTRAINT NN_CONSULT_SERVICE NOT NULL,
  DATE_CONSULTATION  DATE          CONSTRAINT NN_CONSULT_DATE NOT NULL,
  HEURE_CONSULTATION VARCHAR2(5)   CONSTRAINT NN_CONSULT_HEURE NOT NULL,
  MOTIF              VARCHAR2(250) CONSTRAINT NN_CONSULT_MOTIF NOT NULL,
  DIAGNOSTIC         VARCHAR2(500),
  OBSERVATIONS       VARCHAR2(1000),
  DUREE_MINUTES      NUMBER(3),
  TYPE_CONSULTATION  VARCHAR2(20) DEFAULT 'NORMALE' NOT NULL,
  MONTANT_HONORAIRE  NUMBER(10,2) DEFAULT 0 NOT NULL,
  CONSTRAINT UQ_CONSULT_RDV UNIQUE (ID_RDV),
  CONSTRAINT FK_CONSULT_RDV FOREIGN KEY (ID_RDV)
    REFERENCES RENDEZ_VOUS(ID_RDV),
  CONSTRAINT FK_CONSULT_PATIENT FOREIGN KEY (ID_PATIENT)
    REFERENCES PATIENT(ID_PATIENT),
  CONSTRAINT FK_CONSULT_MEDECIN FOREIGN KEY (ID_MEDECIN)
    REFERENCES MEDECIN(ID_MEDECIN),
  CONSTRAINT FK_CONSULT_SERVICE FOREIGN KEY (ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE),
  CONSTRAINT CK_CONSULT_DUREE CHECK (DUREE_MINUTES BETWEEN 5 AND 480),
  CONSTRAINT CK_CONSULT_TYPE CHECK
    (TYPE_CONSULTATION IN ('NORMALE','URGENCE','CONTROLE','TELECONSULTATION')),
  CONSTRAINT CK_CONSULT_MONTANT CHECK (MONTANT_HONORAIRE >= 0)
);

CREATE TABLE ORDONNANCE (
  ID_ORDONNANCE      NUMBER(8)     CONSTRAINT PK_ORDONNANCE PRIMARY KEY,
  ID_CONSULTATION    NUMBER(8)     CONSTRAINT NN_ORDO_CONSULT NOT NULL,
  DATE_ORDONNANCE    DATE DEFAULT SYSDATE NOT NULL,
  COMMENTAIRE        VARCHAR2(500),
  CONSTRAINT FK_ORDO_CONSULT FOREIGN KEY (ID_CONSULTATION)
    REFERENCES CONSULTATION(ID_CONSULTATION)
);

CREATE TABLE MEDICAMENT (
  ID_MEDICAMENT      NUMBER(6)     CONSTRAINT PK_MEDICAMENT PRIMARY KEY,
  NOM_MEDICAMENT     VARCHAR2(100) CONSTRAINT NN_MEDICAMENT_NOM NOT NULL,
  FAMILLE            VARCHAR2(60),
  FORME              VARCHAR2(30),
  DOSAGE_STANDARD    VARCHAR2(30),
  PRIX_UNITAIRE      NUMBER(10,2)  CONSTRAINT NN_MEDICAMENT_PRIX NOT NULL,
  STOCK              NUMBER(8) DEFAULT 0 NOT NULL,
  SEUIL_ALERTE       NUMBER(8) DEFAULT 10 NOT NULL,
  DATE_PEREMPTION    DATE,
  CONSTRAINT UQ_MEDICAMENT UNIQUE (NOM_MEDICAMENT, FORME, DOSAGE_STANDARD),
  CONSTRAINT CK_MEDICAMENT_PRIX CHECK (PRIX_UNITAIRE >= 0),
  CONSTRAINT CK_MEDICAMENT_STOCK CHECK (STOCK >= 0),
  CONSTRAINT CK_MEDICAMENT_SEUIL CHECK (SEUIL_ALERTE >= 0)
);

CREATE TABLE PRESCRIPTION (
  ID_ORDONNANCE      NUMBER(8),
  ID_MEDICAMENT      NUMBER(6),
  POSOLOGIE          VARCHAR2(150) CONSTRAINT NN_PRESCRIPTION_POSO NOT NULL,
  DUREE_JOURS        NUMBER(4),
  QUANTITE           NUMBER(5) DEFAULT 1 NOT NULL,
  INSTRUCTIONS       VARCHAR2(300),
  CONSTRAINT PK_PRESCRIPTION PRIMARY KEY (ID_ORDONNANCE, ID_MEDICAMENT),
  CONSTRAINT FK_PRESCRIPTION_ORDO FOREIGN KEY (ID_ORDONNANCE)
    REFERENCES ORDONNANCE(ID_ORDONNANCE),
  CONSTRAINT FK_PRESCRIPTION_MED FOREIGN KEY (ID_MEDICAMENT)
    REFERENCES MEDICAMENT(ID_MEDICAMENT),
  CONSTRAINT CK_PRESCRIPTION_DUREE CHECK (DUREE_JOURS IS NULL OR DUREE_JOURS > 0),
  CONSTRAINT CK_PRESCRIPTION_QTE CHECK (QUANTITE > 0)
);

CREATE TABLE ACTE (
  ID_ACTE            NUMBER(6)     CONSTRAINT PK_ACTE PRIMARY KEY,
  NOM_ACTE           VARCHAR2(100) CONSTRAINT NN_ACTE_NOM NOT NULL,
  CATEGORIE          VARCHAR2(40)  CONSTRAINT NN_ACTE_CAT NOT NULL,
  COUT_ACTE          NUMBER(10,2)  CONSTRAINT NN_ACTE_COUT NOT NULL,
  CONSTRAINT UQ_ACTE_NOM UNIQUE (NOM_ACTE),
  CONSTRAINT CK_ACTE_COUT CHECK (COUT_ACTE >= 0)
);

CREATE TABLE ACTE_CONSULTATION (
  ID_CONSULTATION    NUMBER(8),
  ID_ACTE            NUMBER(6),
  QUANTITE           NUMBER(4) DEFAULT 1 NOT NULL,
  RESULTAT           VARCHAR2(500),
  CONSTRAINT PK_ACTE_CONSULT PRIMARY KEY (ID_CONSULTATION, ID_ACTE),
  CONSTRAINT FK_ACTECONS_CONSULT FOREIGN KEY (ID_CONSULTATION)
    REFERENCES CONSULTATION(ID_CONSULTATION),
  CONSTRAINT FK_ACTECONS_ACTE FOREIGN KEY (ID_ACTE)
    REFERENCES ACTE(ID_ACTE),
  CONSTRAINT CK_ACTECONS_QTE CHECK (QUANTITE > 0)
);

CREATE TABLE HOSPITALISATION (
  ID_HOSPITALISATION NUMBER(8)     CONSTRAINT PK_HOSPITALISATION PRIMARY KEY,
  ID_PATIENT         NUMBER(6)     CONSTRAINT NN_HOSPIT_PATIENT NOT NULL,
  ID_SERVICE         NUMBER(4)     CONSTRAINT NN_HOSPIT_SERVICE NOT NULL,
  ID_CHAMBRE         NUMBER(5)     CONSTRAINT NN_HOSPIT_CHAMBRE NOT NULL,
  DATE_ENTREE        DATE          CONSTRAINT NN_HOSPIT_ENTREE NOT NULL,
  DATE_SORTIE        DATE,
  MOTIF_ENTREE       VARCHAR2(300) CONSTRAINT NN_HOSPIT_MOTIF NOT NULL,
  DIAGNOSTIC_SORTIE  VARCHAR2(500),
  COUT_JOURNALIER    NUMBER(10,2)  CONSTRAINT NN_HOSPIT_COUT NOT NULL,
  STATUT             VARCHAR2(20) DEFAULT 'EN_COURS' NOT NULL,
  CONSTRAINT FK_HOSPIT_PATIENT FOREIGN KEY (ID_PATIENT)
    REFERENCES PATIENT(ID_PATIENT),
  CONSTRAINT FK_HOSPIT_SERVICE FOREIGN KEY (ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE),
  CONSTRAINT FK_HOSPIT_CHAMBRE_SERVICE FOREIGN KEY (ID_CHAMBRE, ID_SERVICE)
    REFERENCES CHAMBRE(ID_CHAMBRE, ID_SERVICE),
  CONSTRAINT CK_HOSPIT_DATES CHECK (DATE_SORTIE IS NULL OR DATE_SORTIE >= DATE_ENTREE),
  CONSTRAINT CK_HOSPIT_COUT CHECK (COUT_JOURNALIER > 0),
  CONSTRAINT CK_HOSPIT_STATUT CHECK (STATUT IN ('EN_COURS','SORTI','TRANSFERE','ANNULE'))
);

CREATE TABLE ANALYSE (
  ID_ANALYSE         NUMBER(6)     CONSTRAINT PK_ANALYSE PRIMARY KEY,
  NOM_ANALYSE        VARCHAR2(100) CONSTRAINT NN_ANALYSE_NOM NOT NULL,
  CATEGORIE          VARCHAR2(50),
  PRIX_ANALYSE       NUMBER(10,2)  CONSTRAINT NN_ANALYSE_PRIX NOT NULL,
  DELAI_HEURES       NUMBER(5),
  CONSTRAINT UQ_ANALYSE_NOM UNIQUE (NOM_ANALYSE),
  CONSTRAINT CK_ANALYSE_PRIX CHECK (PRIX_ANALYSE >= 0),
  CONSTRAINT CK_ANALYSE_DELAI CHECK (DELAI_HEURES IS NULL OR DELAI_HEURES > 0)
);

CREATE TABLE DEMANDE_ANALYSE (
  ID_DEMANDE         NUMBER(8)     CONSTRAINT PK_DEMANDE_ANALYSE PRIMARY KEY,
  ID_CONSULTATION    NUMBER(8)     CONSTRAINT NN_DEMANDE_CONSULT NOT NULL,
  ID_ANALYSE         NUMBER(6)     CONSTRAINT NN_DEMANDE_ANALYSE NOT NULL,
  DATE_DEMANDE       DATE DEFAULT SYSDATE NOT NULL,
  DATE_RESULTAT      DATE,
  RESULTAT           VARCHAR2(1000),
  STATUT             VARCHAR2(20) DEFAULT 'DEMANDEE' NOT NULL,
  CONSTRAINT FK_DEMANDE_CONSULT FOREIGN KEY (ID_CONSULTATION)
    REFERENCES CONSULTATION(ID_CONSULTATION),
  CONSTRAINT FK_DEMANDE_ANALYSE FOREIGN KEY (ID_ANALYSE)
    REFERENCES ANALYSE(ID_ANALYSE),
  CONSTRAINT UQ_DEMANDE UNIQUE (ID_CONSULTATION, ID_ANALYSE),
  CONSTRAINT CK_DEMANDE_DATES CHECK (DATE_RESULTAT IS NULL OR DATE_RESULTAT >= DATE_DEMANDE),
  CONSTRAINT CK_DEMANDE_STATUT CHECK
    (STATUT IN ('DEMANDEE','EN_COURS','TERMINEE','ANNULEE'))
);

CREATE TABLE FACTURE (
  ID_FACTURE         NUMBER(8)     CONSTRAINT PK_FACTURE PRIMARY KEY,
  ID_PATIENT         NUMBER(6)     CONSTRAINT NN_FACTURE_PATIENT NOT NULL,
  ID_CONSULTATION    NUMBER(8),
  ID_HOSPITALISATION NUMBER(8),
  DATE_FACTURE       DATE DEFAULT SYSDATE NOT NULL,
  MONTANT_TOTAL      NUMBER(12,2)  CONSTRAINT NN_FACTURE_MONTANT NOT NULL,
  REMISE             NUMBER(5,2) DEFAULT 0 NOT NULL,
  STATUT             VARCHAR2(20) DEFAULT 'EMISE' NOT NULL,
  CONSTRAINT FK_FACTURE_PATIENT FOREIGN KEY (ID_PATIENT)
    REFERENCES PATIENT(ID_PATIENT),
  CONSTRAINT FK_FACTURE_CONSULT FOREIGN KEY (ID_CONSULTATION)
    REFERENCES CONSULTATION(ID_CONSULTATION),
  CONSTRAINT FK_FACTURE_HOSPIT FOREIGN KEY (ID_HOSPITALISATION)
    REFERENCES HOSPITALISATION(ID_HOSPITALISATION),
  CONSTRAINT CK_FACTURE_SOURCE CHECK (
    (ID_CONSULTATION IS NOT NULL AND ID_HOSPITALISATION IS NULL)
    OR (ID_CONSULTATION IS NULL AND ID_HOSPITALISATION IS NOT NULL)
  ),
  CONSTRAINT CK_FACTURE_MONTANT CHECK (MONTANT_TOTAL >= 0),
  CONSTRAINT CK_FACTURE_REMISE CHECK (REMISE BETWEEN 0 AND 100),
  CONSTRAINT CK_FACTURE_STATUT CHECK
    (STATUT IN ('EMISE','PARTIELLE','PAYEE','ANNULEE'))
);

CREATE TABLE PAIEMENT (
  ID_PAIEMENT        NUMBER(8)     CONSTRAINT PK_PAIEMENT PRIMARY KEY,
  ID_FACTURE         NUMBER(8)     CONSTRAINT NN_PAIEMENT_FACTURE NOT NULL,
  DATE_PAIEMENT      DATE DEFAULT SYSDATE NOT NULL,
  MONTANT            NUMBER(12,2)  CONSTRAINT NN_PAIEMENT_MONTANT NOT NULL,
  MODE_PAIEMENT      VARCHAR2(20)  CONSTRAINT NN_PAIEMENT_MODE NOT NULL,
  REFERENCE_PAIEMENT VARCHAR2(50),
  CONSTRAINT FK_PAIEMENT_FACTURE FOREIGN KEY (ID_FACTURE)
    REFERENCES FACTURE(ID_FACTURE),
  CONSTRAINT CK_PAIEMENT_MONTANT CHECK (MONTANT > 0),
  CONSTRAINT CK_PAIEMENT_MODE CHECK
    (MODE_PAIEMENT IN ('ESPECES','CARTE','CHEQUE','VIREMENT','ASSURANCE'))
);

CREATE TABLE JOURNAL_OPERATION (
  ID_JOURNAL         NUMBER(10)    CONSTRAINT PK_JOURNAL PRIMARY KEY,
  UTILISATEUR        VARCHAR2(30)  DEFAULT USER NOT NULL,
  DATE_OPERATION     DATE DEFAULT SYSDATE NOT NULL,
  TYPE_OPERATION     VARCHAR2(10)  NOT NULL,
  NOM_TABLE          VARCHAR2(30)  NOT NULL,
  CLE_LIGNE          VARCHAR2(100),
  ANCIENNE_VALEUR    VARCHAR2(1000),
  NOUVELLE_VALEUR    VARCHAR2(1000),
  CONSTRAINT CK_JOURNAL_TYPE CHECK (TYPE_OPERATION IN ('INSERT','UPDATE','DELETE'))
);

PROMPT ============================================================
PROMPT  CREATION DES SEQUENCES
PROMPT ============================================================

CREATE SEQUENCE SEQ_CLINIQUE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PERSONNE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PATIENT START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDECIN START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHAMBRE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RDV START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONSULTATION START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDONNANCE START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICAMENT START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACTE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HOSPITALISATION START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANALYSE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEMANDE_ANALYSE START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACTURE START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAIEMENT START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_JOURNAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT ============================================================
PROMPT  INDEX UTILES AUX JOINTURES ET RECHERCHES
PROMPT ============================================================

CREATE INDEX IDX_PATIENT_PERSONNE ON PATIENT(ID_PERSONNE);
CREATE INDEX IDX_MEDECIN_PERSONNE ON MEDECIN(ID_PERSONNE);
CREATE INDEX IDX_MEDECIN_CLINIQUE ON MEDECIN(ID_CLINIQUE);
CREATE INDEX IDX_SERVICE_CLINIQUE ON SERVICE(ID_CLINIQUE);
CREATE INDEX IDX_RDV_PATIENT ON RENDEZ_VOUS(ID_PATIENT);
CREATE INDEX IDX_RDV_DATE ON RENDEZ_VOUS(DATE_RDV);
CREATE INDEX IDX_CONSULT_PATIENT ON CONSULTATION(ID_PATIENT);
CREATE INDEX IDX_CONSULT_MEDECIN ON CONSULTATION(ID_MEDECIN);
CREATE INDEX IDX_CONSULT_DATE ON CONSULTATION(DATE_CONSULTATION);
CREATE INDEX IDX_HOSPIT_PATIENT ON HOSPITALISATION(ID_PATIENT);
CREATE INDEX IDX_DEMANDE_CONSULT ON DEMANDE_ANALYSE(ID_CONSULTATION);
CREATE INDEX IDX_FACTURE_PATIENT ON FACTURE(ID_PATIENT);
CREATE INDEX IDX_PAIEMENT_FACTURE ON PAIEMENT(ID_FACTURE);

PROMPT ============================================================
PROMPT  VERIFICATIONS DU SCHEMA
PROMPT ============================================================

SELECT table_name FROM user_tables ORDER BY table_name;
SELECT sequence_name FROM user_sequences ORDER BY sequence_name;
SELECT constraint_type, COUNT(*) AS nombre
FROM user_constraints
GROUP BY constraint_type
ORDER BY constraint_type;

COMMIT;

PROMPT ============================================================
PROMPT  SCHEMA EL_SAHA CREE AVEC SUCCES
PROMPT ============================================================
